apiVersion: v1
annotations:
 catalog.cattle.io/featured: "1"
name: pycharm
version: 0.3
appVersion: 2025.3
description: Pycharm
icon: file://charts/pycharm/v0.3/logo.svg
keywords:
- Remote desktop
- Webrtc
- 3D Acceleration
- applications
- VNC
- Pycharm
home: https://cerit.io
sources:
- https://github.com/CERIT-SC/rancher-apps
maintainers:
- name: CERIT-SC
  email: root@cerit-sc.cz
engine: gotpl
