apiVersion: v1
name: blender
version: 1.2
appVersion: 4.4.3
description: Blender
icon: file://charts/blender/v1.2/logo.svg
keywords:
- Remote desktop
- Blender
- Webrtc
- 3D Acceleration
- applications
home: https://cerit.io
sources:
- https://github.com/CERIT-SC/rancher-apps
maintainers:
- name: CERIT-SC
  email: root@cerit-sc.cz
engine: gotpl
