apiVersion: v2
name: wave
description: wave chart that runs on kubernetes
icon: file://charts/wave/v4.4.1/logo.svg
version: 4.4.1
appVersion: v0.10.0
keywords:
  - wave
  - kubernetes
home: https://github.com/wave-k8s/wave
sources:
- https://github.com/wave-k8s/wave
maintainers:
- name: CERIT-SC
  email: root@cerit-sc.cz
engine: gotpl
