apiVersion: v2
name: n8n
description: Flexible AI workflow automation for technical teams.
type: application
version: 1.1
appVersion: 2.4.5
icon: file://charts/n8n/v1.1/n8n-logo.svg
keywords:
- AI
- LLMs
- AI Agents
- applications
home: https://cerit.io
sources:
- https://github.com/CERIT-SC/rancher-apps
maintainers:
- name: CERIT-SC
  email: root@cerit-sc.cz
engine: gotpl
