apiVersion: v2
annotations:
  catalog.cattle.io/kube-version: '>=1.21-0'
  catalog.cattle.io/release-name: ""
name: n8n
description: Flexible AI workflow automation for technical teams.
type: application
version: 1.0
appVersion: 1.114.4
icon: file://charts/n8n/v1.0/n8n-logo.svg
keywords:
- AI
- LLMs
- AI Agents
- applications
home: https://cerit.io
sources:
- https://github.com/CERIT-SC/rancher-apps
maintainers:
- name: CERIT-SC
  email: root@cerit-sc.cz
engine: gotpl
